### ISSUE TITLE
Edit account information

### ISSUE THREAD

**Issue by kyBa-Le** [kyBa-Le/Gogo#27]

**Comment by binhhoang249** [comment]
1. Gán link home vào logo ở header
2. Tạo thêm một icon cho user sau khi đăng nhập [hàm ẩn hiện]
3. Ở nút đăng nhập đăng kí [thêm hiệu ứng:hover]
4. Tạo cho trang riêng cho Edit information [hiển thị thông tin người dùng, không bao gồm mật khẩu], thêm 1 ô avatar[có chỉnh sửa luôn]
